function expTable = table_summary( expData, stats )

% *Note: for publication, consider splitting Exp ID into Date and Subject 

% Generate Summary Table for all Experiments

rowDist = ones(numel(expData),1);
%'Index',mat2cell((1:numel(expData))',rowDist),...
S = struct(...
    'Experiment_ID',{expData.sub_dir}',...
    'Cell_Type',{expData.cellType}',...
    'nTrials',mat2cell(stats.behavior.all.trialsCompleted.data,rowDist),...
    'nBlocks',mat2cell(stats.behavior.all.blocksCompleted.data,rowDist),...
    'nCells',  mat2cell(stats.imaging.all.inclCells.data,rowDist)...
    );

expTable = struct2table(S);
expTable.Properties.RowNames = mat2cell(num2str((1:numel(expData))'),rowDist);