function fig = plot_behByTrial(trialData,trials,tlabel,time_range)
%%% plot_session_beh_vert %
%PURPOSE:   Plot behavioral variables from auditory discrimination session by trial
%AUTHORS:   MJ Siniscalchi & AC Kwan 190624
%
%INPUT ARGUMENTS
%   trialData:    Structure generated by flex_getSessionData().
%   trials:       Structure generated by flex_getTrialMasks().
%   tlabel:       Text to put as title of the plot
%   time_range:   Time in seconds to plot, e.g., [-2 6], around the cue

    fig = figure;
    title({tlabel;'{\color{red}L Licks} {\color{blue}R Licks} {\color[rgb]{1 0.8 0.8}Upsweep} {\color[rgb]{0.8 0.8 1}Downsweep} {\color[rgb]{0.5 1 1}Reward} '});
    hold on;
    for j = 1:numel(trialData.cue)
        t0 = trialData.cueTimes(j);
        
        %Shaded area for cue
        if trials.upsweep(j)
            color = 'r';
        elseif trials.downsweep(j)
            color = 'b';
        end
        eventTime = trialData.cueTimes(j);
        eventDur = trialData.outcomeTimes(j)-trialData.cueTimes(j);
        p = fill([eventTime-t0 eventTime+eventDur-t0...
            eventTime+eventDur-t0 eventTime-t0],...
            [j-0.5 j-0.5 j+0.5 j+0.5],color);
        set(p,'Edgecolor','none','FaceAlpha',0.2);
        
        %Shaded area for outcome
        if trials.hit(j)
            color = 'c';
        else
            color = 'w';
        end   
        eventTime = trialData.outcomeTimes(j);
        eventDur = 0.5;
        p = fill([eventTime-t0 eventTime+eventDur-t0...
            eventTime+eventDur-t0 eventTime-t0],...
            [j-0.5 j-0.5 j+0.5 j+0.5],color);
        set(p,'Edgecolor','none','FaceAlpha',0.2);
        
        %Plot tick marks for licks
        LL = trialData.leftlickTimes{j}; RL = trialData.rightlickTimes{j};
        plot([LL; LL],j+[-0.5*ones(size(LL)); 0.5*ones(size(LL))],'r','LineWidth',1);
        plot([RL; RL],j+[-0.5*ones(size(RL)); 0.5*ones(size(RL))],'b','LineWidth',1);
    end
    
    xlim([time_range(1),time_range(2)]);
    ylim([0 numel(trialData.cue)]);
    xlabel('Time from sound cue (s)');
    ylabel('Trial number');
    axis ij square;
end


