%%% smLearning_setPathList
%
%PURPOSE:   Set up paths to run all analyses of longitudinal imaging &
%               behavior during learning of sensorimotor associations.
%AUTHORS: MJ Siniscalchi & AC Kwan, 190701
%
%--------------------------------------------------------------------------
function data_dir = pathlist_smLearning

% Get name of computer to specify paths
switch getenv('COMPUTERNAME')
    case 'STELLATE' %KwanLab desktop, 'STELLATE'
        data_dir = 'J:\Data & Analysis\Sensorimotor Learning';
        code_dir = 'J:\Documents\MATLAB\GitHub\Sensorimotor-Learning';
    case 'WINDOWS-CVO3377' %HP Laptop
        data_dir = 'C:\Users\Michael\Documents\Data & Analysis\Sensorimotor Learning';
        code_dir = 'C:\Users\Michael\Documents\MATLAB\GitHub\Sensorimotor-Learning';
    case 'KWANLAB-PC' %KwanLab PC
        data_dir = 'D:\JenHau\Sensorimotor Learning';
        code_dir = 'D:\JenHau\Sensorimotor-Learning'; %Should be main code directory; sub directories specified below....
end

% add the paths needed for this code
path_list = {...
    code_dir;...
    fullfile(code_dir,'behavior');...
    fullfile(code_dir,'image stack processing');...
    fullfile(code_dir,'image stack processing','scim_3');...
    fullfile(code_dir,'cell fluo');...
    fullfile(code_dir,'fluo analyses');...
    fullfile(code_dir,'validation');...
    fullfile(code_dir,'figures');...
    fullfile(code_dir,'summary');...
    fullfile(code_dir,'common functions');...
    fullfile(code_dir,'common functions','cbrewer');...
    };
addpath(path_list{:});