function fig = plot_longRegrResults( cell_data )
% plotReg_longitudinal()
%PURPOSE:   Plot linear regression results from multiple sessions of longitudinal calcium imaging
%AUTHOR:    MJ Siniscalchi 190327
%
%INPUT ARGUMENTS
%   reg_data:     2D struct (nCells,nSessions) aggregated from data generated by linear_regr.m
%   pvalThresh:   Threshold value to deem whether p-values are significant
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.

% 
fig = figure;
factors = {'Choice','Outcome','Interaction'};

for i = 1:numel(factors)
    subplot(1,3,i);
    ax(i) = gca;
    for j = 1:numel(cell_data)
        plot(j,cell_data(j).nMod(i),'b.','MarkerSize',10); hold on
    end
    axis square; box off;
    yLims(:,i) = ax(i).YLim;  %Get limits to scale all plots equally
end

for i = 1:numel(factors)
ax(i).Title.String = factors{i};
ax(i).YLim = [min(yLims(:)) max(yLims(:))];
ax(i).XLim = [0 7];
ax(i).XLabel.String = 'Session Number';
ax(i).XTick = 1:6;
end
ax(1).YLabel.String = 'Number of cells modulated';




