function fig = plotReg_longitudinal( reg_data, pvalThresh, tlabel, xtitle)
% plotReg_longitudinal()
%PURPOSE:   Plot linear regression results from multiple sessions of longitudinal calcium imaging
%AUTHOR:    MJ Siniscalchi 190327
%
%INPUT ARGUMENTS
%   reg_data:     2D struct (nCells,nSessions) aggregated from data generated by linear_regr.m
%   pvalThresh:   Threshold value to deem whether p-values are significant
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.

% 
figure;
factors = {'Choice','Outcome','Interaction'};
for i = 1:numel(factors)
subplot(1,3,i);
ax(i+6) = gca;
plot(nMod.(factors{i}));
axis square; box off;
yLims(:,i) = ax(i+6).YLim;  %Get limits to scale all plots equally 
end

for i = 1:numel(factors)
ax(i+6).Title.String = factors{i};
ax(i+6).YLim = [min(yLims(:)) max(yLims(:))];
%ax(i+6).XLabel.String = 'Accuracy criterion (%)';
%ax(i+6).XTickLabel = [expData(:).criterion];
ax(i+6).XLabel.String = 'Session Number';
ax(i+6).XTick = 1:6;
end
ax(7).YLabel.String = 'Number of cells modulated';




