function output = calc_preference(input1,input2)
% % calc_selectivity %
%PURPOSE:   Calculate selectivity, based on PSTHs from two conditions
%               Selectivity = (A-B)/(A+B)
%AUTHORS:   AC Kwan 171216, edited by MJ Siniscalchi 190517
%
%INPUT ARGUMENTS
%   input1:       Structure generated by get_psth(), condition 1, e.g., left choice
%   input2:       Structure generated by get_psth(), condition 2, e.g., right choice
%
%OUTPUT ARGUMENTS
%   output:       Structure containing the analysis results

output.signal       = (input1.signal-input2.signal) ./ (input1.signal+input2.signal);
output.t            = input1.t;
output.subset_label = {input1.subset_label, input2.subset_label};
output.nEvent       = [input1.nEvent, input2.nEvent];
output.meanByTrial  = nanmean(output.signal(output.t>=0));

end