%%% get_sessionFluoData
%
%PURPOSE: Fetch stack and ROIs selected using cellROI.m, 
%           along with optional neuropil masks.
%
%AUTHOR: MJ Siniscalchi, 190507
%
%INPUT ARGS: char 'roi_path', the path to a directory containing all ROI files,
%               as well as the MAT file 'roiData.mat'. All files generated
%               using the GUI, cellROI.m.
%
%OUTPUTS: double 'stack', the full time-lapse image stack.
%         struct 'cells' containing these fields:           
%           'cellMasks', an X x Y x nROIs logical array containing the logical indices for each ROI.
%           'subtractMasks', the same for each neuropil mask, if desired. 
%           'cellIDs', an array of character vectors corresponding to 
%               the cell IDs from cellROI; also found in the filenames.
%
%**FUTURE EDIT: 'stack' can be a cell array of partial stacks to accomodate resonant scanning...    
%
%--------------------------------------------------------------------------
     
function [ stack, cells ] = get_sessionFluoData( roi_path, file_paths )

if nargin<2
    file_paths = [];
end

%Get image stack and roi files generated by cellROI.m
if isempty(file_paths)
    S = load(fullfile(roi_path,'roiData.mat'),'pathname','filename');
    disp(['Loading ' S.pathname S.filename '...']);
    stack = double(loadtiffseq(S.pathname,S.filename));
else
    
end

%Populate 3D array containing all cell masks
fileList = dir(fullfile(roi_path,'*cell*.mat'));
fileIDs = {};
for j = 1:numel(fileList)
    S = load(fullfile(roi_path, fileList(j).name));
    cells.roimask{j} = S.bw;
    cells.cellf{j} = S.cellf;
    cells.cellID{j} = num2str(fileList(j).name(end-6:end-4));
    if isfield(S,'subtractmask')
        cells.subtractmask{j} = S.subtractmask;
    else
        cells.subtractmask{j} = false(size(cells.roimask{j}));
        fileIDs{numel(fileIDs)+1} = num2str(fileList(j).name(end-6:end-4));
    end
end

if ~isempty(fileIDs)
    disp('Warning: No neuropil masks found in the following files:');
    disp(fileIDs');
end