function bootAvg = getTrialBoot ( trial_dff, subset_label, params)
%%% getTrialBoot
%
%PURPOSE:  
%AUTHORS:   MJ Siniscalchi 190911, concept based on get_PSTH by AC Kwan 170515
%
%INPUT ARGUMENTS
%   trial_dff:      Matrix of aligned dF/F signals, eg, generated by 'alignCellFluo.m'
%                       with rows taken only from the relevant subset of trials.
%   subset_label:   Character array identifying 
%   params.window:  the time window around which to align signal
%
%   params.CI:                  confidence interval (CI)
%   params.numBootstrapRepeat:  number of bootstrap repeats to estimate CI
%
%OUTPUTS
%
%
%--------------------------------------------------------------------------
%%

% Unpack some variables from structure
nTrials = size(trial_dff,1);
nReps = params.nReps;
CI = params.CI;
    
%% Estimate mean dF/F and confidence intervals using the bootstrap
bootRep = NaN(nReps,size(trial_dff,2)); %An array of bootstrap replicates
for i = 1:nReps
    
    %Draw a random sample with replacement and estimate mean
    bootSample = trial_dff(randsample(nTrials,nTrials,'true'),:);
    bootRep(i,:) = nanmean(bootSample);

end

%Estimate grand mean and confidence interval
bootAvg.subset_label = subset_label;
bootAvg.signal = nanmean(bootRep,1); %Use trial avg instead of boot avg
bootAvg.CI(1,:) = prctile(bootRep,50+CI/2,1);
bootAvg.CI(2,:) = prctile(bootRep,50-CI/2,1);
bootAvg.N = nTrials;
